import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types --language ts ./types`.

export enum MindBlogTags {
    PERSONAL = "personal",
    PROFESSIONAL = "professional",
    HEALTH = "health",
    LIFESTYLE = "lifestyle",
    TECHNOLOGY = "technology"
}

export enum MindBlogStatus {
    DRAFT = "Draft",
    PUBLISHED = "Published",
    DELETED = "Deleted"
}

export type MindBlog = Models.Row & {
    title: string;
    content: string;
    authorId: number;
    publishDate: string;
    tags: MindBlogTags | null;
    likes: number | null;
    commentsEnabled: boolean | null;
    slug: string;
    status: MindBlogStatus;
}
